(() => {
 'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const paths={grid:'M3 3h7v7H3Zm11 0h7v7h-7ZM3 14h7v7H3Zm11 0h7v7h-7Z',menu:'M4 6h16M4 12h16M4 18h16',bell:'M6 9a6 6 0 0 1 12 0v6l2 3H4l2-3ZM10 21h4',arrow:'M5 12h14m-6-6 6 6-6 6',calendar:'M4 5h16v16H4ZM4 10h16M8 2v6m8-6v6',people:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21v-3a8 8 0 0 1 16 0v3',chart:'M4 21V10m8 11V3m8 18v-7',settings:'M4 7h16M4 17h16M8 4v6m8 4v6'};
 const icon=n=>`<span class="ps-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.grid}"/></svg></span>`;
 const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));}catch{}};
 const presets=['Today','Yesterday','Today and yesterday','Last 7 days','Last 14 days','Last 28 days','Last 30 days','This week','Last week','This month','Last month','Year to date','Custom'];
 const date=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 function range(preset,custom){let to=new Date(),from=new Date();to.setHours(0,0,0,0);from.setHours(0,0,0,0);const days=n=>from.setDate(from.getDate()-n);if(preset==='Custom'&&custom)return custom;if(preset==='Yesterday'){days(1);to=new Date(from);}else if(preset==='Today and yesterday')days(1);else if(preset.startsWith('Last ')&&preset.endsWith(' days'))days(Number(preset.split(' ')[1])-1);else if(preset==='This week'||preset==='Last week'){days((from.getDay()+6)%7);if(preset==='Last week'){days(7);to=new Date(from);to.setDate(to.getDate()+6);}}else if(preset==='This month')from.setDate(1);else if(preset==='Last month'){from.setDate(1);from.setMonth(from.getMonth()-1);to=new Date(from.getFullYear(),from.getMonth()+1,0);}else if(preset==='Year to date')from=new Date(from.getFullYear(),0,1);return{from:date(from),to:date(to)};}
 function mount(options){
  const {container,content,nav,onView}=options,uid=options.user||options.workspace||'pulsify',key='pulsify:workspace-location:'+uid;
  container.classList.add('ps-shell');container.innerHTML=`<div class="ps-overlay"></div><aside class="ps-sidebar"><button class="ps-switch" aria-label="Switch workspace" aria-haspopup="dialog">${esc(options.workspace||'Pulsify')} <span aria-hidden="true">⌄</span></button><nav class="ps-nav" aria-label="Workspace views">${nav.map(g=>`${g.label?`<p>${esc(g.label)}</p>`:''}${g.items.map(i=>`<button data-view="${esc(i.id)}" title="${esc(i.label)}">${icon(i.icon||'grid')}<span>${esc(i.label)}</span></button>`).join('')}`).join('')}</nav><div class="ps-sidebar-footer">Private workspace<br>Connected to Pulsify</div></aside><div class="ps-workspace"><header class="ps-header"><button class="ps-control ps-collapse" aria-label="Toggle sidebar">${icon('menu')}</button><span class="ps-header-title">Overview</span><button class="ps-control ps-dates" aria-haspopup="dialog">${icon('calendar')}<span class="ps-date-label"></span></button><button class="ps-control ps-notifications" aria-label="Notifications" aria-haspopup="dialog">${icon('bell')}</button><button class="ps-avatar" aria-label="Account menu" aria-haspopup="dialog">${esc((options.workspace||'P').slice(0,1).toUpperCase())}</button></header><main class="ps-main"></main></div>`;
  const main=container.querySelector('main');if(content)main.append(content);
  const locationState=read(key,{});let active='',clients=options.clients||[],profile=options.user||'',currentPreset=read('pulsify:range:'+uid,'Last 30 days'),custom=read('pulsify:custom-range:'+uid,null),popup;
  const flat=nav.flatMap(g=>g.items),title=id=>flat.find(i=>i.id===id)?.label||id.replaceAll('/',' / ');
  function close(){if(popup){popup.close();popup.remove();popup=null;}}
  function pop(html){close();popup=document.createElement('dialog');popup.className='ps-popover';popup.innerHTML=html;document.body.append(popup);popup.showModal();popup.addEventListener('click',e=>{if(e.target===popup){const b=popup.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)close();}});return popup;}
  function sync(id,label){active=id;container.querySelector('.ps-header-title').textContent=label||title(id);document.title=(label||title(id))+' — '+(options.workspace||'Pulsify')+' | Pulsify';container.querySelectorAll('[data-view]').forEach(b=>{const selected=b.dataset.view===id;b.classList.toggle('active',selected);if(selected)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});write(key,{view:id,clientId:options.clientId||null});main.classList.remove('view-enter');void main.offsetWidth;main.classList.add('view-enter');}
  function go(id,{push=true}={}){if(options.canLeave?.()===false)return;container.classList.remove('mobile-open');const result=onView?.(id,main);if(result===false)return;sync(id);if(push)history.pushState({psView:id},'',location.pathname+location.search);}
  container.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const item=flat.find(i=>i.id===b.dataset.view);if(item?.href){window.open(item.href,'_blank','noopener');return;}go(b.dataset.view);});
  container.querySelector('.ps-collapse').onclick=()=>{if(innerWidth<1024)container.classList.toggle('mobile-open');else{container.classList.toggle('collapsed');write('pulsify:sidebar:'+uid,container.classList.contains('collapsed'));}};
  container.querySelector('.ps-overlay').onclick=()=>container.classList.remove('mobile-open');if(read('pulsify:sidebar:'+uid,false)&&innerWidth>=1024)container.classList.add('collapsed');
  container.querySelector('.ps-notifications').onclick=()=>pop('<h2>Notifications</h2><p>You’re all caught up.</p>');
  container.querySelector('.ps-avatar').onclick=()=>{const p=pop(`<h2>${esc(options.workspace||'Pulsify')}</h2><p>${esc(profile)}</p><button class="ps-control" data-signout>Sign out</button>`);p.querySelector('[data-signout]').onclick=()=>{Object.keys(localStorage).filter(k=>k.startsWith('pulsify:analytics:')||k.startsWith('pulsify:bootstrap:')).forEach(k=>localStorage.removeItem(k));options.signOut?.();};};
  container.querySelector('.ps-switch').onclick=()=>{const p=pop(`<h2>Workspaces</h2><div class="ps-presets">${options.operator===false?'':'<button data-client="">Pulsify</button>'}${clients.map(c=>`<button data-client="${esc(c.client)}">${esc(c.client_name||c.client)}</button>`).join('')}</div>`);p.querySelectorAll('[data-client]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await options.onWorkspace?.(b.dataset.client);close();}catch(e){b.disabled=false;const note=document.createElement('p');note.textContent=e.message;p.append(note);}});};
  function publishRange(){const selected=range(currentPreset,custom);window.PulsifyRange={...selected,preset:currentPreset,contains(value){const day=String(value||'').slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(day)&&day>=selected.from&&day<=selected.to;}};window.dispatchEvent(new CustomEvent('pulsify:range',{detail:window.PulsifyRange}));options.onRange?.(selected);}
  const rangeLabel=()=>{container.querySelector('.ps-date-label').textContent=currentPreset;queueMicrotask(publishRange);};
  container.querySelector('.ps-dates').setAttribute('aria-label','Date range');
  rangeLabel();container.querySelector('.ps-dates').onclick=()=>{
   let selected=currentPreset,chosen=range(selected,custom),p=pop('<div class="ps-date-layout"><div class="ps-presets"></div><div class="ps-calendars"></div></div><div class="ps-range-footer"><span></span><button class="ps-control" data-cancel>Cancel</button><button class="ps-control" data-update>Update</button></div>'),selectingEnd=false,month=new Date();
   function render(){p.querySelector('.ps-presets').innerHTML=presets.map(n=>`<button data-preset="${n}" aria-pressed="${selected===n}">${n}</button>`).join('');p.querySelector('.ps-presets').querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=b.dataset.preset;chosen=range(selected,custom);render();});p.querySelector('.ps-calendars').innerHTML=[-1,0].map(offset=>{const m=new Date(month.getFullYear(),month.getMonth()+offset,1),blank=(m.getDay()+6)%7,count=new Date(m.getFullYear(),m.getMonth()+1,0).getDate();return`<div class="ps-calendar"><div style="display:flex;justify-content:space-between;align-items:center"><button class="ps-control" data-month="-1" aria-label="Previous month">‹</button><strong>${m.toLocaleDateString('en',{month:'short',year:'numeric'})}</strong><button class="ps-control" data-month="1" aria-label="Next month">›</button></div><div class="ps-calendar-grid">${['M','T','W','T','F','S','S'].map(n=>'<span>'+n+'</span>').join('')}${'<span></span>'.repeat(blank)}${Array.from({length:count},(_,i)=>{const value=date(new Date(m.getFullYear(),m.getMonth(),i+1));return`<button data-day="${value}" aria-label="${value}" class="${value>=chosen.from&&value<=chosen.to?'selected':''}">${i+1}</button>`;}).join('')}</div></div>`;}).join('');p.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{month.setMonth(month.getMonth()+Number(b.dataset.month));render();});p.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{selected='Custom';if(!selectingEnd){chosen={from:b.dataset.day,to:b.dataset.day};selectingEnd=true;}else{chosen.to=b.dataset.day;if(chosen.from>chosen.to)[chosen.from,chosen.to]=[chosen.to,chosen.from];selectingEnd=false;}render();});p.querySelector('.ps-range-footer span').textContent='Selected range: '+chosen.from+' to '+chosen.to;}
   render();p.querySelector('[data-cancel]').onclick=close;p.querySelector('[data-update]').onclick=()=>{currentPreset=selected;custom=chosen;write('pulsify:range:'+uid,selected);write('pulsify:custom-range:'+uid,custom);rangeLabel();close();};
  };
  window.addEventListener('popstate',e=>{if(e.state?.psView)go(e.state.psView,{push:false});});
  const params=new URLSearchParams(location.search),initial=params.get('view')||locationState.view||options.initial||flat[0]?.id;
  params.delete('view');history.replaceState({psView:initial},'',location.pathname+(params.size?'?'+params.toString():''));
  const api={main,go,sync,setClients(list){clients=list;},setUser(value){profile=value;},settings(){main.innerHTML='<h1>Settings</h1><p class="ps-subtitle">Preferences for this device.</p><section class="ps-settings"><h2 style="margin-top:0">Appearance</h2><p>Choose how your workspace looks.</p><div class="ps-segments">'+['light','dark','system'].map(t=>`<button class="ps-control" data-theme-mode="${t}" aria-pressed="false">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')+'</div></section>';const apply=()=>main.querySelectorAll('[data-theme-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.themeMode===(localStorage.getItem('theme')||'dark'))));main.querySelectorAll('[data-theme-mode]').forEach(b=>b.onclick=()=>{PulsifyTheme.apply(b.dataset.themeMode);apply();});apply();},banner(name,exit){let b=container.querySelector('.ps-banner');if(!b){b=document.createElement('div');b.className='ps-banner';container.querySelector('.ps-header').after(b);}b.innerHTML='<span>Viewing as '+esc(name)+'.</span><button>Exit</button>';b.querySelector('button').onclick=exit;}};
  // Call after the adapter has stored the returned object.
  queueMicrotask(()=>go(initial,{push:false}));return api;
 }
 window.PulsifyShell={mount,icon,esc,read,write,range};
})();
